# Generated by Django 4.0.3 on 2022-03-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emoji_message_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emoji',
        ),
        migrations.DeleteModel(
            name='Emoji',
        ),
    ]
