# Generated by Django 4.0.3 on 2022-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_pointsreceived_profile_pointstosend'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pointTotal',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
