# Generated by Django 4.0.3 on 2022-04-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pointTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
