# Generated by Django 4.0.4 on 2022-04-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_publicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastMessageSent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
