# Generated by Django 4.0.4 on 2022-04-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_profile_lastmessagesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastMessageSent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
