# Generated by Django 4.0.3 on 2022-04-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_purchaseitem_options_purchaseitem_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploaded/'),
        ),
    ]
