# Generated by Django 4.0.3 on 2022-04-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='image/SmileAssetRed', null=True, upload_to='images/'),
        ),
    ]
