# Generated by Django 4.0.3 on 2022-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='/images/StoreAssets/SmileAssetRed.png', null=True, upload_to=''),
        ),
    ]
